数组与矩阵运算

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
a=np.random.randn(10)

In [3]:
a

array([-1.26569053, -1.85567619,  0.10191021, -0.17458952,  0.81437512,
        0.3845939 ,  0.29417098, -1.28079832, -1.41358804,  0.17092334])

In [4]:
b=np.random.randint(10,size=10)

In [6]:
c=b.reshape(2,5)

In [7]:
c

array([[3, 7, 4, 1, 4],
       [6, 2, 6, 7, 4]])

In [8]:
d=np.random.randint(10,size=10).reshape(2,5)

In [9]:
c+d

array([[ 5, 11, 10,  2,  6],
       [ 9,  2, 14, 13,  7]])

In [10]:
c*d

array([[ 6, 28, 24,  1,  8],
       [18,  0, 48, 42, 12]])

In [11]:
a/b

array([-0.42189684, -0.2650966 ,  0.02547755, -0.17458952,  0.20359378,
        0.06409898,  0.14708549, -0.21346639, -0.20194115,  0.04273084])

In [13]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [14]:
C=np.mat(c)

In [15]:
D=np.mat(d)

In [16]:
C+D

matrix([[ 5, 11, 10,  2,  6],
        [ 9,  2, 14, 13,  7]])

In [17]:
C*D

ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

Array常用函数

In [18]:
np.unique(a)

array([-1.85567619, -1.41358804, -1.28079832, -1.26569053, -0.17458952,
        0.10191021,  0.17092334,  0.29417098,  0.3845939 ,  0.81437512])

In [19]:
sum(a)

-4.224369057857143

In [20]:
a

array([-1.26569053, -1.85567619,  0.10191021, -0.17458952,  0.81437512,
        0.3845939 ,  0.29417098, -1.28079832, -1.41358804,  0.17092334])

In [21]:
sum(c)

array([ 9,  9, 10,  8,  8])

In [22]:
c.max()

7

In [25]:
max(c[0,:])

7

# array的input和output

In [26]:
import pickle

In [27]:
f=open("c.pkl","wb")

In [28]:
pickle.dump(c,f)

In [29]:
f=open("c.pkl","rb")

In [30]:
pickle.load(f)

EOFError: Ran out of input

In [31]:
f.close()

In [32]:
np.save("one_array",c)

In [35]:
np.load("one_array.npy")

array([[3, 7, 4, 1, 4],
       [6, 2, 6, 7, 4]])