In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [6]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.concatenate([arr1,arr2])  #链接两个矩阵参数axis=1/0 横向/纵向

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.concatenate([arr1,arr2],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [11]:
s1 = Series([1,2,3],index=['x','y','z'])
s2 = Series([4,5],index=['a','b'])

In [12]:
s1

x    1
y    2
z    3
dtype: int64

In [13]:
s2

a    4
b    5
dtype: int64

In [16]:
pd.concat([s1,s2],axis=1)

e:\vs2017\vs2017\python36_64\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
a  NaN  4.0
b  NaN  5.0
x  1.0  NaN
y  2.0  NaN
z  3.0  NaN

In [20]:
df1 = DataFrame(np.random.randn(4,3),columns=['x','y','z'])
df2 = DataFrame(np.random.randn(3,3),columns=['x','y','a'])

In [21]:
df1

x         y         z
0 -0.010269 -0.275917 -0.204888
1  0.199562 -0.607877  0.135465
2 -0.066551 -0.631607  2.682208
3 -0.657585 -1.664094 -0.183902

In [22]:
df2

x         y         a
0  2.192911 -0.157128 -1.318723
1 -0.368407 -0.063269 -0.448686
2 -0.012601  0.360140  0.347143

In [23]:
pd.concat([df1,df2])

e:\vs2017\vs2017\python36_64\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


a         x         y         z
0       NaN -0.010269 -0.275917 -0.204888
1       NaN  0.199562 -0.607877  0.135465
2       NaN -0.066551 -0.631607  2.682208
3       NaN -0.657585 -1.664094 -0.183902
0 -1.318723  2.192911 -0.157128       NaN
1 -0.448686 -0.368407 -0.063269       NaN
2  0.347143 -0.012601  0.360140       NaN

# combine

In [25]:
s1 = Series([2,np.nan,4,np.nan],index=['a','b','c','d'])
s2 = Series([1,2,3,4],index=['a','b','c','d'])

In [26]:
s1.combine_first(s2) #用s2填充s1

a    2.0
b    2.0
c    4.0
d    4.0
dtype: float64

In [27]:
s1

a    2.0
b    NaN
c    4.0
d    NaN
dtype: float64

In [28]:
s2

a    1
b    2
c    3
d    4
dtype: int64

In [29]:
df1 = DataFrame({
    'x':[1,np.nan,3,np.nan],
    'y':[5,np.nan,7,np.nan],
    'z':[9,np.nan,11,np.nan]
})

In [30]:
df1

x    y     z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [35]:
df2=DataFrame({'z':[10,np.nan,12,np.nan],
    "a":[1,2,3,4]})

In [36]:
df1.combine_first(df2)

a    x    y     z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN   NaN
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN   NaN

In [37]:
df2

z  a
0  10.0  1
1   NaN  2
2  12.0  3
3   NaN  4